== Configuration du plugin Virtuel

Le plugin ne nécessite aucune configuration, il faut juste l'activer.

== Ajout d'un équipement

Pour ajouter un nouveau *virtuel*, vous devez accéder à la page du plugin, à partir du menu *Plugins->Programmation->Virtuel*.
Il suffit alors de cliquer sur *Ajouter* et de donner un nom à votre équipement virtuel. Vous accéderez ensuite à sa configuration.

== Configuration des équipements

En haut à droite vous avez accès à 3 boutons :

* *Importer équipement* : Permet de dupliquer automatiquement un équipement existant dans un virtuel (permet de gagner du temps pour scinder un équipement en 2 par exemple).
* *Dupliquer* : Permet de dupliquer l'équipement courant.
* *Configuration avancée* : Permet d'afficher les options avancées de l'équipement.
* *Supprimer* : Permet de supprimer le virtuel.
* *Sauvegarder* : Permet de sauvegarder les changements effectués.

[TIP]
Comme à beaucoup d'endroits sur Jeedom, mettre la souris tout à gauche permet de faire apparaître un menu d'accès rapide (vous pouvez à partir de votre profil le laisser toujours visible).

=== Onglet Equipement

Vous retrouvez la liste des virtuels créés à partir du menu *Plugins->Programmation->Virtuel*. Une fois que vous cliquez sur un déjà créé, vous retrouvez ces différents paramètres :

* *Nom de l'équipement virtuel* : Nom de votre équipement virtuel.
* *Objet parent* : Indique l'objet parent auquel appartient l'équipement.
* *Catégorie* : Les catégories de l'équipement (plusieurs choix sont possibles).
* *Activer* : Cochez cette case pour rendre votre équipement actif,
* *Visible* : Cochez cette case pour le rendre visible sur le dashboard notamment,
* *Auto-actualisation (cron)* : Permet d'actualiser la valeur du virtuel. Le *?* permet de programmer une tâche cron. Vous pouvez laisser de champ vide également.
* *URL de retour* : Ce lien peut être utilisé pour accéder à la valeur de ce virtuel par une commande API.

[NOTE]
Attention à bien rajouter un `/jeedom` après `\#IP_JEEDOM#` si nécessaire.

=== Onglet Commandes

En haut à droite, deux boutons essentiels :

* *Ajouter une commande virtuelle* : Permet d'ajouter une commande de type action rattachée à ce virtuel.
* *Ajouter une info virtuelle* : Permet d'ajouter une commande de type info rattachée à ce virtuel.

Vous retrouvez un tableau présentant les différentes commandes disponibles pour ce virtuel. Voici les différentes colonnes et leurs paramètres :

* *Nom* : Le nom affiché sur le dashboard.
* *Sous-Type* : Le type et le sous-type de la commande.
* *Valeur* : Suivant le type de commande, vous pouvez retrouver les paramètres suivants :
  ** Pour une commande *action* :
    *** *Nom information* : Nom de la commande information qui sera modifiée par cette commande action.
    *** *Valeur* : Valeur que prendra la commande information précisée dans *Nom information*.
  ** Pour une commande *information* :
    *** *Calcul* : Permet de mettre comme valeur le résultat d'un calcul.
    *** *Valeur retour d'état* : Permet de donner une valeur par défaut que la commande information prendra au bout d'un certain temps.
    *** *Durée avant retour d'état* : Durée, en minutes, au bout de laquelle la commande information prendra la *valeur retour d'état*.
* *Unité* : unité de la donnée (peut être vide),
* *Paramètres* :
  ** *Afficher* : Permet d'afficher la donnée sur le dashboard.
  ** *Historiser* : Permet d'historiser la donnée.
  ** *Inverser* : Permet, pour une donnée binaire, d'inverser l'information.
  ** *Min/Max* : bornes de la donnée (peuvent être vides),
  ** *Liste déroulante* :
  ** *Valeur de l'information* :
* *Autre* :
  ** *Configuration avancée* (petites roues crantées) : Permet d'afficher la configuration avancée de la commande (méthode d'historisation, widget...).
  ** *Tester* : Permet de tester la commande.
  ** *Supprimer* (signe -) : Permet de supprimer la commande.

Vous trouverez des exemples de configurations sur link:examples.asciidoc[cette page].
